<h1>Manage Items</h1>

<table>
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Price</th>
			<th>Description</th>
			<th>Image</th>
			<th>Keywords</th>
			<th>Category</th>
			<th>Edit/Delete</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($items as $item => $properties) : ?>
			<tr>
			<?php foreach ($properties as $column => $value) : ?>
				<?php if (!($column == "short_description")) : ?>
					<?php if($column == "item_id") : ?>
						<td align="center">
							<form class="" action="admin_view_all_items.php" method="post">
								<?= $value; ?>
								<input type="hidden" name="id" value="<?= $value; ?>"></td>
					<?php elseif ($column == "item_cost") : ?>
						<td align="center"><?=$value;?></td>
					<?php elseif ($column == "item_name") : ?>
							<td><a href="item.php?item=<?= $value; ?>"><?=$value;?></a></td>
					<?php elseif ($column == "img_path") : ?>
						<td><img class="productThumb" src="<?= $value;?>"></td>
					<?php elseif ($column == "category") : ?>
						<td><?=$value;?></td>
						<td>
							<button class="blueButton" type="submit" name="submit" value="edit">Edit</button>
							<button class="redButton" type="submit" name="submit" value="delete">Delete</button>
							</form>
						</td>
					<?php else : ?>
						<td><?= $value; ?></td>

					<?php endif; ?>
				<?php endif; ?>
			<?php endforeach; ?>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>
